filebeat.inputs:
# - type: container
- type: filestream
  id: my-filestream-id
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

output.logstash:
  hosts: ["192.168.1.37:5044"]