version: '3.6'

services:
  elasticsearch:
    # image: elasticsearch:7.16.2
    # image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      discovery.type: single-node
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk-network

  # kibana:
  #   # image: kibana:7.16.2
  #   # image: docker.elastic.co/kibana/kibana:7.16.2
  #   image: docker.elastic.co/kibana/kibana:8.13.2
  #   container_name: kibana
  #   restart: always       
  #   ports:
  #   - '5601:5601'
  #   environment:
  #     - ELASTICSEARCH_URL=http://elasticsearch:9200
  #     - ELASTIC_USERNAME=elastic
  #     - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
  #   depends_on:
  #     - elasticsearch  
  #   networks:
  #     - elk-network
  
  # logstash:
  #   # image: logstash:7.16.2
  #   # image: docker.elastic.co/logstash/logstash:7.16.2
  #   image: docker.elastic.co/logstash/logstash:8.13.2
  #   container_name: logstash
  #   restart: always
  #   volumes:
  #   - ./logstash/:/logstash_dir
  #   command: logstash -f /logstash_dir/logstash.conf 
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #   - '9600:9600'
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - elk-network
  #   output:
  #     elasticsearch:
  #       hosts: ["elasticsearch:9200"]  # Assuming Elasticsearch on port 9200
  #       user: "elastic"
  #       password: "${ELASTIC_PASSWORD}"
  #       index: "%{my_index_name}"

volumes:
  elasticsearch_data: {}

networks:
  elk-network: